spring.application.name=commerce
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.datasource.url=jdbc:postgresql://localhost:5432/commerce
server.port=8081

spring.messages.basename=messages
spring.messages.encoding=UTF-8
