spring:
  config:
    activate:
      on-profile: local

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: user
    password: secret123
    driver-class-name: org.postgresql.Driver

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket: project-files
