spring.application.name=commerce
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=update


spring.messages.basename=messages
spring.messages.encoding=UTF-8
